# Generated by Django 4.2 on 2023-05-08 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=350)),
                ('apellidop', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=350)),
                ('zona', models.CharField(max_length=100)),
                ('forma_pago', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=350)),
                ('imagen', models.CharField(max_length=100)),
                ('video', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('vigencia', models.DateField()),
                ('visibilidad', models.BooleanField(default=True)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=6)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellidop', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=40)),
                ('contraseña', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AnuncioContra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contra', models.DateField()),
                ('vigencia', models.DateField()),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=6)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.anuncio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='anuncio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
    ]
