# Generated by Django 4.2.1 on 2023-06-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_anuncio_imagen_alter_usuario_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='video',
            field=models.FileField(null=True, upload_to='videos_uploaded'),
        ),
    ]
