# Generated by Django 4.2.1 on 2023-06-11 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_anuncio_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='usuario',
        ),
    ]
